### ISSUE TITLE
Integrate IPFS with ergoutils

### ISSUE THREAD

**Issue by anon-real** [anon-real/ErgoUtils#1]
Instead of using imgbb for issuing artworks (picture, audio), integrate IPFS or any other decentralized approach in a way that the auction house doesn't break.

**Comment by arobsn** [comment]
Working on it. ;)

**Comment by catalyst244** [comment]
we're working on it

**Comment by anon-real** [comment]
https://github.com/anon-real/ErgoUtils/pull/2#issuecomment-917667534

**Comment by anon-real** [comment]
Already implemented.
